name: Bug
description: Something is broken
labels: ["type:bug"]
body:
  - type: textarea
    attributes: { label: Steps to Reproduce }
  - type: textarea
    attributes: { label: Expected vs Actual }
  - type: textarea
    attributes: { label: Logs/KO refs }