name: Feature Request
description: Propose a new feature or enhancement
title: "[FEATURE] "
labels: ["type:feat", "status:needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for suggesting a new feature! Please provide the details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, users have to... It would be better if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: "I propose adding... which would..."
    validations:
      required: true

  - type: textarea
    id: outcome
    attributes:
      label: Expected Outcome
      description: What should happen after implementing this feature?
      placeholder: "After implementation, users should be able to..."
    validations:
      required: true

  - type: textarea
    id: events
    attributes:
      label: Events & Contracts
      description: What events or contract changes are needed?
      placeholder: "This would require new events: ... and contract updates to..."

  - type: textarea
    id: ko-outputs
    attributes:
      label: KO Outputs
      description: What knowledge objects would this feature produce?
      placeholder: "This feature would create KO types: ... stored in ..."

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this feature is complete?
      placeholder: |
        - [ ] Feature works as described
        - [ ] Tests pass
        - [ ] Documentation updated
        - [ ] Events properly typed
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0 - Critical for launch
        - P1 - Important but not blocking
        - P2 - Nice to have
    validations:
      required: true

  - type: dropdown
    id: risk
    attributes:
      label: Risk Level
      description: What is the implementation risk?
      options:
        - Low - Straightforward implementation
        - Medium - Some complexity or unknowns
        - High - Significant complexity or architectural changes
    validations:
      required: true